# Documentation at: https://alacritty.org/config-alacritty.html

import = [
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
   "~/.config/alacritty/catppuccin-mocha.toml"
]
shell = "/usr/local/bin/fish"
live_config_reload = true

[env]
TERM = "alacritty"
#TERM = "xterm-256color"

[window]
# Spread additional padding evenly around the terminal content.
dynamic_padding = true
padding = { x = 3, y = 3 }
startup_mode = "Maximized"
opacity = 0.98
#blur = true
decorations = "Full"

[font]
normal = { family = "MesloLGS NF", style = "Regular" }
bold = { family = "MesloLGS NF", style = "Bold" }
italic = { family = "MesloLGS NF", style = "Italic" }
bold_italic = { family = "MesloLGS NF", style = "Bold Italic" }
size = 14.0
#offset = { x = 0, y = 14 }
#glyph_offset = { x = 0, y = 7 }

[cursor]
style = { shape = "Underline", blinking = 'Always'}
vi_mode_style = { shape = "Beam", blinking = 'Always'}

